### ISSUE TITLE
Argument of type '"completed"' is not assignable to parameter of type 'QueueListenerType'.ts(2345)

### ISSUE THREAD

**Issue by nambirajan-goxai** [anchan828/nest-bull#1358]
@BullQueueEvents(queueName)
export class ConnectorEvents {
  constructor(
  ) {}
//Argument of type '"completed"' is not assignable to parameter of type 'QueueListenerType'.ts
  @BullQueueEventProcess("completed")
  public async process(job): Promise<void> {

  }
}

**Comment by anchan828** [comment]
Thanks for the report.
There seem to be some changes, so I will respond.

**Comment by anchan828** [comment]
@nambirajan-goxai Hi, Fixed this issue and published a new package version.

https://www.npmjs.com/package/@anchan828/nest-bullmq/v/1.1.0

I added new decorators for listeners. Please see Readme.

https://github.com/anchan828/nest-bull/tree/master/packages/bullmq#add-workerqueuequeueevents-listeners

**Comment by anchan828** [comment]
If you encounter any new problems, please create a new issue.
