### ISSUE TITLE
Services are undefined after updating to NestJs 6

### ISSUE THREAD

**Issue by cschroeter** [anchan828/nest-bull#27]
Hey - first of all thanks for this awesome library.

Unfortunately I discovered an isse after updating to NestJS 6. Services in the BullQueueProcess are not defined anymore :(

```typescript
@BullQueue({ name: JOB_QUEUE })
export class JobQueue {
 constructor(private readonly service: Service) {
    console.log('Service', { service }); // service defined
  }

  @BullQueueProcess()
  process(job: Job<any>): void {
    console.log('Service', { service }); // here the service is not defined
  }

**Comment by anchan828** [comment]
Hi @cschroeter, 
Thank you for your report.
I want to fix this bug. Which version of nest-bull do you use?

I created test for this issue, but passed it 🤔
https://github.com/anchan828/nest-bull/blob/issue-27/src/issues/issue-27.spec.ts#L18

**Comment by cschroeter** [comment]
@anchan828 Thanks for the reply. I will provide a minimal repository to reproduce the issue.

I am using a more complex module structure , including `forwardRef(() => Module)`. Not sure if its related to it

**Comment by cschroeter** [comment]
@anchan828 I tried to reprodcue with a nested modules and also `forwardRef()` but it still works - so I guess the error is somewhere else :/ but anyway thank you for your time

**Comment by cschroeter** [comment]
After I've spend some more time researching I could create a small repo to reproduce the issue.
https://github.com/cschroeter/bull-bug/
@anchan828  Would be nice if you could have a look :)
