### ISSUE TITLE
Services are undefined after updating to NestJs 6 

### ISSUE THREAD

**Issue by cschroeter** [anchan828/nest-bull#45]
After I've spend some more time researching I could create a small repo to reproduce the issue.
https://github.com/cschroeter/bull-bug/
@anchan828 Would be nice if you could have a look :)

**Comment by anchan828** [comment]
@cschroeter Thank you for your report. I will check.

**Comment by anchan828** [comment]
Fixed this issue in #47. please try again after installing 0.3.5
@cschroeter Thank you very much for your cooperation!

**Comment by cschroeter** [comment]
@anchan828 Thank you so much. It works :)
